description: 'heavyweight shared database'
metadatastore:
    module: 'databroker.headersource.mongo'
    class: 'MDS'
    config:
        host: 'arcturus.xray.aps.anl.gov'
        port: 27017
        database: 'metadatastore-production-v1'
        timezone: 'US/Central'
assets:
    module: 'databroker.assets.mongo'
    class: 'Registry'
    config:
        host: 'arcturus.xray.aps.anl.gov'
        port: 27017
        database: 'filestore-production-v1'
